version: '3.0'
services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: false
